# Flight/ Weather/ Aircraft data: Chicago (ORD)

## Project Description

### Import Libraries

In [5]:
import numpy as np
import pandas as pd
import glob
import os

### Data ingestion

In [7]:
# Ingesting flight data for Chicago(ORD)
# Departures
# Airlines: American Airlines, Delta Airlines, Southwest Airlines, and United Airlines
# 2022 - 2026
ORD_flights_files = sorted(glob.glob("Data/ORD_Dep_*_Flight_Stats.csv"))
print(f"Found {len(ORD_flights_files)} ORD Arrival file(s):")
for f in ORD_flights_files:
    print(" ", f)

ORD_flights = pd.concat(
    (pd.read_csv(f, skiprows=7) for f in ORD_flights_files), ignore_index=True)
print(f"Total flight rows loaded: {len(ORD_flights)}")

Found 4 ORD Arrival file(s):
  Data/ORD_Dep_AA_Flight_Stats.csv
  Data/ORD_Dep_DL_Flight_Stats.csv
  Data/ORD_Dep_UA_Flight_Stats.csv
  Data/ORD_Dep_WN_Flight_Stats.csv
Total flight rows loaded: 674692

In [8]:
# ingesting chicago weather data 
# 01/01/2022 - 07/09/2026
chi_weather_files = sorted(glob.glob("Data/ORD_Weather_*.psv") + glob.glob("Data/ORD_Weather_2022"))
print(f"Found {len(chi_weather_files)} Chicago weather file(s):")
for f in chi_weather_files:
    print(" ", f)

chi_weather = pd.concat(
    (pd.read_csv(f, sep="|") for f in chi_weather_files), ignore_index=True)
print(f"Total weather rows loaded: {len(chi_weather)}")

Found 5 Chicago weather file(s):
  Data/ORD_Weather_2022
  Data/ORD_Weather_2023.psv
  Data/ORD_Weather_2024.psv
  Data/ORD_Weather_2025.psv
  Data/ORD_Weather_2026.psv

/var/folders/br/86kbstxj04q8nx12fhbxhryw0000gn/T/ipykernel_95825/2159083874.py:9: DtypeWarning: Columns (13,19,43,49,55,67,77,80,82,83,86,88,91,97,101,103,104,106,119,122,124,128,130,133,217,223,229,241,247,253,318) have mixed types. Specify dtype option on import or set low_memory=False.
  (pd.read_csv(f, sep="|") for f in chi_weather_files), ignore_index=True)
/var/folders/br/86kbstxj04q8nx12fhbxhryw0000gn/T/ipykernel_95825/2159083874.py:9: DtypeWarning: Columns (13,19,43,55,61,67,77,80,82,83,86,88,91,97,103,128,130,133,217,223,229,241,247,253) have mixed types. Specify dtype option on import or set low_memory=False.
  (pd.read_csv(f, sep="|") for f in chi_weather_files), ignore_index=True)
/var/folders/br/86kbstxj04q8nx12fhbxhryw0000gn/T/ipykernel_95825/2159083874.py:9: DtypeWarning: Columns (13,19,43,55,61,67,77,80,82,83,86,88,91,97,101,103,104,106,128,130,133,217,223,229,235,241,247,253,258,259) have mixed types. Specify dtype option on import or set low_memory=False.
  (pd.read_csv(f, sep="|") for f in chi_weather_files), ignore_index=True)
/var/folders/br/86kbstxj04q8nx12fhbxhryw0000gn/T/ipykernel_95825/2159083874.py:9: DtypeWarning: Columns (77,80,82,89,92,94,95,98,100,101,104,106,119,122,124,128,130,240,246,252) have mixed types. Specify dtype option on import or set low_memory=False.
  (pd.read_csv(f, sep="|") for f in chi_weather_files), ignore_index=True)
/var/folders/br/86kbstxj04q8nx12fhbxhryw0000gn/T/ipykernel_95825/2159083874.py:9: DtypeWarning: Columns (24,36,42,77,80,82,83,86,88,89,92,94,95,98,100,101,104,106,119,122,124,128,130,132,149,151,152,154,156,158,160,192,194,196,240,246,252,258,264,276,278,280,282,284,286,320,322) have mixed types. Specify dtype option on import or set low_memory=False.
  (pd.read_csv(f, sep="|") for f in chi_weather_files), ignore_index=True)

Total weather rows loaded: 67043

In [9]:
# ingesting aircraft data
aircraft = pd.read_csv("Data/MASTER.txt", sep=",", encoding="utf-8-sig", low_memory=False)
print(f"Aircraft registry rows loaded: {len(aircraft)}")

Aircraft registry rows loaded: 313930

### Data Preprocessing

In [10]:
#shape and dtypes for flights
print("Shape of flights df:", ORD_flights.shape)
print("Data types:")
print(ORD_flights.dtypes)
ORD_flights.head()

Shape of flights df: (674692, 17)
Data types:
Carrier Code                                 object
Date (MM/DD/YYYY)                            object
Flight Number                               float64
Tail Number                                  object
Destination Airport                          object
Scheduled departure time                     object
Actual departure time                        object
Scheduled elapsed time (Minutes)            float64
Actual elapsed time (Minutes)               float64
Departure delay (Minutes)                   float64
Wheels-off time                              object
Taxi-Out time (Minutes)                     float64
Delay Carrier (Minutes)                     float64
Delay Weather (Minutes)                     float64
Delay National Aviation System (Minutes)    float64
Delay Security (Minutes)                    float64
Delay Late Aircraft Arrival (Minutes)       float64
dtype: object

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,AA,01/01/2022,298.0,N819AN,MIA,14:25,16:47,184.0,203.0,142.0,17:33,46.0,0.0,114.0,19.0,0.0,28.0
1,AA,01/01/2022,299.0,N802AN,DFW,15:05,15:05,150.0,210.0,0.0,16:00,55.0,0.0,0.0,60.0,0.0,0.0
2,AA,01/01/2022,304.0,N321RL,DCA,10:51,10:50,118.0,110.0,-1.0,11:14,24.0,0.0,0.0,0.0,0.0,0.0
3,AA,01/01/2022,309.0,N581UW,MCO,10:35,10:56,162.0,154.0,21.0,11:10,14.0,0.0,0.0,0.0,0.0,0.0
4,AA,01/01/2022,335.0,N908NN,MIA,11:55,11:53,186.0,202.0,-2.0,12:25,32.0,0.0,0.0,0.0,0.0,0.0

In [11]:
print("Shape of weather df:", chi_weather.shape)
print("Data types:")
print(chi_weather.dtypes)
chi_weather.head()

Shape of weather df: (67043, 329)
Data types:
STATION                   object
Station_name              object
DATE                      object
Year                       int64
Month                      int64
                          ...
REM_Measurement_Code     float64
REM_Quality_Code         float64
REM_Report_Type           object
REM_Source_Code          float64
REM_Source_Station_ID     object
Length: 329, dtype: object

,STATION,Station_name,DATE,Year,Month,Day,Hour,Minute,LATITUDE,LONGITUDE,...,precipitation_24_hour_Quality_Code,precipitation_24_hour_Report_Type,precipitation_24_hour_Source_Code,precipitation_24_hour_Source_Station_ID,REM,REM_Measurement_Code,REM_Quality_Code,REM_Report_Type,REM_Source_Code,REM_Source_Station_ID
0,USW00094846,CHICAGO OHARE INTL AP,2022-01-01T00:00:00,2022,1,1,0,0,41.9603,-87.9317,...,NaN,NaN,NaN,NaN,SYN08672530 31120 80308 10056 20039 39797 4003...,NaN,NaN,FM12,223.0,ICAO-KORD
1,USW00094846,CHICAGO OHARE INTL AP,2022-01-01T00:06:00,2022,1,1,0,6,41.9603,-87.9317,...,NaN,NaN,NaN,NaN,MET09712/31/21 18:06:03 SPECI KORD 010006Z 030...,NaN,NaN,FM16,343.0,725300-94846
2,USW00094846,CHICAGO OHARE INTL AP,2022-01-01T00:30:00,2022,1,1,0,30,41.9603,-87.9317,...,NaN,NaN,NaN,NaN,MET09312/31/21 18:30:03 SPECI KORD 010030Z 350...,NaN,NaN,FM16,343.0,725300-94846
3,USW00094846,CHICAGO OHARE INTL AP,2022-01-01T00:51:00,2022,1,1,0,51,41.9603,-87.9317,...,NaN,NaN,NaN,NaN,MET10312/31/21 18:51:03 METAR KORD 010051Z 040...,NaN,NaN,FM15,343.0,725300-94846
4,USW00094846,CHICAGO OHARE INTL AP,2022-01-01T01:51:00,2022,1,1,1,51,41.9603,-87.9317,...,NaN,NaN,NaN,NaN,MET10012/31/21 19:51:03 METAR KORD 010151Z 020...,NaN,NaN,FM15,343.0,725300-94846

In [12]:
print("Shape of aircraft df:", aircraft.shape)
print("Data types:")
print(aircraft.dtypes)
aircraft.head()

Shape of aircraft df: (313930, 35)
Data types:
N-NUMBER             object
SERIAL NUMBER        object
MFR MDL CODE         object
ENG MFR MDL          object
YEAR MFR             object
TYPE REGISTRANT      object
NAME                 object
STREET               object
STREET2              object
CITY                 object
STATE                object
ZIP CODE             object
REGION               object
COUNTY               object
COUNTRY              object
LAST ACTION DATE      int64
CERT ISSUE DATE      object
CERTIFICATION        object
TYPE AIRCRAFT        object
TYPE ENGINE           int64
STATUS CODE          object
MODE S CODE           int64
FRACT OWNER          object
AIR WORTH DATE       object
OTHER NAMES(1)       object
OTHER NAMES(2)       object
OTHER NAMES(3)       object
OTHER NAMES(4)       object
OTHER NAMES(5)       object
EXPIRATION DATE      object
UNIQUE ID             int64
KIT MFR              object
 KIT MODEL           object
MODE S CODE HEX      object
Unnamed: 34         float64
dtype: object

,N-NUMBER,SERIAL NUMBER,MFR MDL CODE,ENG MFR MDL,YEAR MFR,TYPE REGISTRANT,NAME,STREET,STREET2,CITY,...,OTHER NAMES(2),OTHER NAMES(3),OTHER NAMES(4),OTHER NAMES(5),EXPIRATION DATE,UNIQUE ID,KIT MFR,KIT MODEL,MODE S CODE HEX,Unnamed: 34
0,100,5334,7100510,17003,1940,1,BENE MARY D ...,PO BOX 329,,KETCHUM,...,...,...,...,...,20270430,600060,,,A004B3,NaN
1,10000,10000,2130004,,,7,9AT LLC ...,511 WEDGEWOOD AVE,,NASHVILLE,...,...,...,...,...,20310831,1443200,,,A00725,NaN
2,10001,A28,9601202,67007,1928,1,STOOS ROBERT A ...,PO BOX 1056,,LAKELAND,...,...,...,...,...,20290228,432072,,,A00726,NaN
3,10004,T18208245,2072738,,,7,ETOS AIR LLC ...,PO BOX 288,,NEW LONDON,...,...,...,...,...,20290331,102879,,,A00729,NaN
4,10006,BG-72,1152020,17026,1955,1,COUTCHES ROBERT HERCULES DBA ...,550 AIRWAY BLVD,,LIVERMORE,...,...,...,...,...,20280229,480110,,,A0072B,NaN

In [13]:
ORD_flights.to_csv("ORD_flights_combined.csv", index=False)

In [14]:
chi_weather.to_csv("chi_weather_combined.csv", index=False)