In [1]:
#import libraries
import pandas as pd
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1783568905.451824   30625 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1783568905.452280   30625 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1783568905.489326   30625 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1783568906.474315   30625 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1783568906.474840   30625 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [2]:
#load data
two_df = pd.read_csv('/home/yvonne_chook/github/207-Summer26-FinalProject-MLModel/Merged_EDA/combined_data/combined_data_2h.csv')

one_df = pd.read_csv('/home/yvonne_chook/github/207-Summer26-FinalProject-MLModel/Merged_EDA/combined_data/combined_data_1h.csv')

- No delay or early departure (0)
- Less than 1 hour delay (1)
- 1–2 hour delay (2)
- 2–3 hour delay (3)
- 3–4 hour delay (4)
- 4–5 hour delay (5)
- 5–6 hour delay (6) 
- More than 6 hour delay (7)
- Flight cancelled (8)

Note to team, there should be a total of 9 outcomes

In [3]:
#currently only 8 displayed
two_df["outcome"].unique()

array([0., 1., 2., 8., 3., 4., 6., 5., 7.])

In [4]:
two_df

,date,scheduled_dep_dt,actual_dep_dt,carrier_code,destination_airport,scheduled_elapsed_time_minutes,year,month,day_of_week,is_weekend,...,dew_point_temperature,relative_humidity,altimeter,aircraft_age,week_num,temperature_dewpoint_spread,airport_delay_average_1h,airport_delay_stddev_1h,airport_departures_observed_1h,departure_delay_minutes
0,2022-01-01,2022-01-01 05:25:00,2022-01-01 05:25:00,WN,DEN,145.0,2022.0,1.0,5.0,1,...,4.4,71.0,1014.2,16.0,1,5.0,0.000000,0.000000,0.0,0.0
1,2022-01-01,2022-01-01 05:55:00,2022-01-01 05:52:00,DL,SLC,118.0,2022.0,1.0,5.0,1,...,4.4,71.0,1014.2,3.0,1,5.0,0.000000,0.000000,0.0,-3.0
2,2022-01-01,2022-01-01 06:00:00,2022-01-01 06:14:00,DL,ATL,272.0,2022.0,1.0,5.0,1,...,5.0,74.0,1014.6,20.0,1,4.4,0.000000,0.000000,0.0,14.0
3,2022-01-01,2022-01-01 06:02:00,2022-01-01 05:56:00,UA,LAX,98.0,2022.0,1.0,5.0,1,...,5.0,74.0,1014.6,6.0,1,4.4,0.000000,0.000000,0.0,-6.0
4,2022-01-01,2022-01-01 06:10:00,2022-01-01 07:51:00,DL,MSP,218.0,2022.0,1.0,5.0,1,...,5.0,74.0,1014.6,24.0,1,4.4,0.000000,0.000000,0.0,101.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335913,2026-04-30,2026-04-30 13:50:00,2026-04-30 14:07:00,UA,SAN,109.0,2026.0,4.0,3.0,0,...,9.4,83.0,1015.6,26.0,18,2.8,28.263158,40.941479,19.0,17.0
335914,2026-04-30,2026-04-30 13:50:00,2026-04-30 14:35:00,UA,LAX,101.0,2026.0,4.0,3.0,0,...,9.4,83.0,1015.6,28.0,18,2.8,28.263158,40.941479,19.0,45.0
335915,2026-04-30,2026-04-30 13:50:00,2026-04-30 14:54:00,UA,MCO,330.0,2026.0,4.0,3.0,0,...,9.4,83.0,1015.6,0.0,18,2.8,28.263158,40.941479,19.0,64.0
335916,2026-04-30,2026-04-30 13:55:00,2026-04-30 13:57:00,UA,HNL,335.0,2026.0,4.0,3.0,0,...,9.4,83.0,1015.6,30.0,18,2.8,31.214286,46.912650,14.0,2.0
335917,2026-04-30,2026-04-30 13:55:00,2026-04-30 13:51:00,DL,JFK,336.0,2026.0,4.0,3.0,0,...,9.4,83.0,1015.6,35.0,18,2.8,31.214286,46.912650,14.0,-4.0

In [5]:
one_df

,date,scheduled_dep_dt,actual_dep_dt,carrier_code,destination_airport,scheduled_elapsed_time_minutes,year,month,day_of_week,is_weekend,...,dew_point_temperature,relative_humidity,altimeter,aircraft_age,week_num,temperature_dewpoint_spread,airport_delay_average_1h,airport_delay_stddev_1h,airport_departures_observed_1h,departure_delay_minutes
0,2022-01-01,2022-01-01 05:25:00,2022-01-01 05:25:00,WN,DEN,145.0,2022.0,1.0,5.0,1,...,5.0,74.0,1014.6,16.0,1,4.4,0.000000,0.000000,0.0,0.0
1,2022-01-01,2022-01-01 05:55:00,2022-01-01 05:52:00,DL,SLC,118.0,2022.0,1.0,5.0,1,...,5.0,74.0,1014.6,3.0,1,4.4,0.000000,0.000000,0.0,-3.0
2,2022-01-01,2022-01-01 06:00:00,2022-01-01 06:14:00,DL,ATL,272.0,2022.0,1.0,5.0,1,...,5.0,77.0,1015.6,20.0,1,3.9,0.000000,0.000000,0.0,14.0
3,2022-01-01,2022-01-01 06:02:00,2022-01-01 05:56:00,UA,LAX,98.0,2022.0,1.0,5.0,1,...,5.0,77.0,1015.6,6.0,1,3.9,0.000000,0.000000,0.0,-6.0
4,2022-01-01,2022-01-01 06:10:00,2022-01-01 07:51:00,DL,MSP,218.0,2022.0,1.0,5.0,1,...,5.0,77.0,1015.6,24.0,1,3.9,0.000000,0.000000,0.0,101.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334081,2026-04-30,2026-04-30 12:37:00,2026-04-30 13:17:00,DL,MSP,223.0,2026.0,4.0,3.0,0,...,9.4,83.0,1015.6,9.0,18,2.8,18.904762,36.750381,21.0,40.0
334082,2026-04-30,2026-04-30 12:40:00,2026-04-30 12:43:00,UA,SNA,102.0,2026.0,4.0,3.0,0,...,9.4,83.0,1015.6,3.0,18,2.8,21.363636,36.845295,22.0,3.0
334083,2026-04-30,2026-04-30 12:45:00,2026-04-30 12:45:00,UA,IAD,312.0,2026.0,4.0,3.0,0,...,9.4,83.0,1015.6,12.0,18,2.8,25.714286,39.733038,21.0,0.0
334084,2026-04-30,2026-04-30 12:45:00,2026-04-30 13:09:00,UA,DEN,164.0,2026.0,4.0,3.0,0,...,9.4,83.0,1015.6,2.0,18,2.8,25.714286,39.733038,21.0,24.0
334085,2026-04-30,2026-04-30 12:55:00,2026-04-30 12:52:00,UA,PHL,334.0,2026.0,4.0,3.0,0,...,9.4,83.0,1015.6,12.0,18,2.8,31.214286,46.912650,14.0,-3.0

In [6]:
#analyze data

two_df.describe()

,scheduled_elapsed_time_minutes,year,month,day_of_week,is_weekend,sched_dep_hour,outcome,days_until_holiday,days_from_holiday,year_mfr,...,dew_point_temperature,relative_humidity,altimeter,aircraft_age,week_num,temperature_dewpoint_spread,airport_delay_average_1h,airport_delay_stddev_1h,airport_departures_observed_1h,departure_delay_minutes
count,335918.000000,335918.000000,335918.000000,335918.000000,335918.00000,335918.000000,335918.000000,335918.000000,335918.000000,335918.000000,...,335918.000000,335918.000000,335918.000000,335918.000000,335918.000000,335918.000000,335918.000000,335918.000000,335918.000000,335918.000000
mean,216.644753,2023.685864,6.381376,2.972943,0.27507,13.015670,0.513167,45.766166,24.240282,2011.127302,...,9.672927,76.998619,1016.309976,12.558562,25.976673,4.252990,10.058537,25.138860,13.681312,10.343515
std,98.440558,1.191044,3.276395,2.004118,0.44655,5.530261,0.878231,36.590218,19.257312,9.165203,...,3.340459,12.846189,4.667695,9.082126,14.324988,2.945768,26.269079,40.680767,8.052340,40.182453
min,48.000000,2022.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1970.000000,...,-7.800000,15.000000,987.500000,0.000000,1.000000,0.000000,-16.000000,0.000000,0.000000,-92.000000
25%,110.000000,2023.000000,4.000000,1.000000,0.00000,8.000000,0.000000,17.000000,9.000000,2002.000000,...,7.800000,70.000000,1013.200000,5.000000,14.000000,2.200000,-2.000000,4.725816,8.000000,-6.000000
50%,223.000000,2024.000000,6.000000,3.000000,0.00000,12.000000,0.000000,36.000000,19.000000,2014.000000,...,10.000000,80.000000,1015.900000,10.000000,26.000000,3.400000,1.733333,13.015226,14.000000,-2.000000
75%,319.000000,2025.000000,9.000000,5.000000,1.00000,18.000000,1.000000,66.000000,36.000000,2019.000000,...,12.200000,86.000000,1019.000000,21.000000,38.000000,5.500000,13.333333,30.536459,19.000000,9.000000
max,386.000000,2026.000000,12.000000,6.000000,1.00000,23.000000,8.000000,148.000000,74.000000,2026.000000,...,20.000000,100.000000,1034.900000,56.000000,53.000000,30.600000,1127.000000,1081.009434,40.000000,1101.000000

In [7]:
#split train validation and test data

#Do this for 2 hr data
two_train_df = two_df[
    (two_df["date"] >= "2022-01-01") &
    (two_df["date"] <= "2024-12-31")
]

two_validation_df = two_df[
    (two_df["date"] >= "2024-01-01") &
    (two_df["date"] <= "2024-12-31")
]

two_test_df = two_df[
    (two_df["date"] >= "2025-01-01") &
    (two_df["date"] <= "2026-06-09")
]

#Do this for 4 hr data
one_train_df = one_df[
    (one_df["date"] >= "2022-01-01") &
    (one_df["date"] <= "2024-12-31")
]

one_validation_df = one_df[
    (one_df["date"] >= "2024-01-01") &
    (one_df["date"] <= "2024-12-31")
]

one_test_df = one_df[
    (one_df["date"] >= "2025-01-01") &
    (one_df["date"] <= "2026-06-09")
]

#print shape of each
print("2hr data:")
print("Train shape:", two_train_df.shape)
print("Validation shape:", two_validation_df.shape)
print("Test shape:", two_test_df.shape)

print("\n1hr data:")
print("Train shape:", one_train_df.shape)
print("Validation shape:", one_validation_df.shape)
print("Test shape:", one_test_df.shape)

2hr data:
Train shape: (236894, 32)
Validation shape: (84932, 32)
Test shape: (99024, 32)

1hr data:
Train shape: (236106, 32)
Validation shape: (84531, 32)
Test shape: (97980, 32)

In [8]:
two_train_df.columns

Index(['date', 'scheduled_dep_dt', 'actual_dep_dt', 'carrier_code',
       'destination_airport', 'scheduled_elapsed_time_minutes', 'year',
       'month', 'day_of_week', 'is_weekend', 'sched_dep_hour', 'outcome',
       'days_until_holiday', 'days_from_holiday', 'year_mfr', 'model',
       'no_seats', 'visibility', 'ceiling_height', 'wind_speed',
       'wind_direction', 'temperature', 'dew_point_temperature',
       'relative_humidity', 'altimeter', 'aircraft_age', 'week_num',
       'temperature_dewpoint_spread', 'airport_delay_average_1h',
       'airport_delay_stddev_1h', 'airport_departures_observed_1h',
       'departure_delay_minutes'],
      dtype='str')

In [9]:
#feature selection

features = [
    "scheduled_elapsed_time_minutes",
    "year",
    "month",
    "day_of_week",
    "is_weekend",
    "sched_dep_hour",
    "days_until_holiday",
    "days_from_holiday",
    "year_mfr",
    "no_seats",
    "visibility",
    "ceiling_height",
    "wind_speed",
    "wind_direction",
    "temperature",
    "dew_point_temperature",
    "relative_humidity",
    "altimeter",
    "aircraft_age",
    "week_num",
    "temperature_dewpoint_spread",
    "airport_delay_average_1h",
    "airport_delay_stddev_1h",
    "airport_departures_observed_1h"
]

target = "departure_delay_minutes"

**2 hour linear regression baseline**

In [10]:
# create X and y
two_X_train = two_train_df[features]
two_y_train = two_train_df[target]

two_X_val = two_validation_df[features]
two_y_val = two_validation_df[target]

two_X_test = two_test_df[features]
two_y_test = two_test_df[target]

# scale features
scaler = StandardScaler()

two_X_train_scaled = scaler.fit_transform(two_X_train)
two_X_val_scaled = scaler.transform(two_X_val)
two_X_test_scaled = scaler.transform(two_X_test)

In [11]:
#build model
def build_model(num_features, learning_rate):
    tf.keras.backend.clear_session()
    tf.random.set_seed(0)

    model = tf.keras.Sequential([
        tf.keras.Input(shape=(num_features,)),
        tf.keras.layers.Dense(units=1, use_bias=True)
    ])

    optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate)

    model.compile(
        optimizer=optimizer,
        loss="mse",
        metrics=["mae"]
    )

    return model

In [ ]:
# train model

two_model = build_model(
    num_features=two_X_train_scaled.shape[1],
    learning_rate=0.01
)

two_trained_model = two_model.fit(
    two_X_train_scaled,
    two_y_train,
    validation_data=(two_X_val_scaled, two_y_val),
    epochs=50,
    batch_size=32,
    verbose = 0
)

#plot output
#plot
plt.plot(two_trained_model.history['loss'], label="Training Loss")
plt.plot(two_trained_model.history['val_loss'], label="Validation Loss")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training and Validation Loss Values Over Epochs")
plt.legend()
plt.show()

E0000 00:00:1783568909.099964   30625 cuda_executor.cc:1737] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1783568909.100349   30677 cuda_executor.cc:1755] Failed to determine cuDNN version (Note that this is expected if the application doesn't link the cuDNN plugin): INTERNAL: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
W0000 00:00:1783568909.115859   30625 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

In [ ]:
#Obtain weight and bias
two_weights, two_bias = two_model.layers[0].get_weights()

#calulate train and test mse

two_train_mse = two_model.evaluate(
    two_X_train_scaled,
    two_y_train,
    verbose = 0 #supress output
)

#Calculate test MSE
two_test_mse = two_model.evaluate(
    two_X_test_scaled,
    two_y_test,
    verbose = 0 # supress output
)

# Learned parameters
print(f"Learned Weights:\n{two_weights}")
print(f"\nLearned Bias:\n{two_bias}")

print(f"Train MSE (standardized): {two_train_mse:.3f}")
print(f"Test MSE (standardized): {two_test_mse:.3f}")
print(f"Difference between test and train MSE: {abs(two_train_mse - two_test_mse):.3f}")

**2 hour linear regression**

In [ ]:
# create X and y
one_X_train = one_train_df[features]
one_y_train = one_train_df[target]

one_X_val = one_validation_df[features]
one_y_val = one_validation_df[target]

one_X_test = one_test_df[features]
one_y_test = one_test_df[target]

# scale features
scaler = StandardScaler()

one_X_train_scaled = scaler.fit_transform(one_X_train)
one_X_val_scaled = scaler.transform(one_X_val)
one_X_test_scaled = scaler.transform(one_X_test)

In [ ]:
# train model

one_model = build_model(
    num_features=one_X_train_scaled.shape[1],
    learning_rate=0.01
)

one_trained_model = one_model.fit(
    one_X_train_scaled,
    one_y_train,
    validation_data=(one_X_val_scaled, one_y_val),
    epochs=50,
    batch_size=32,
    verbose = 0
)

#plot output
#plot
plt.plot(one_trained_model.history['loss'], label="Training Loss")
plt.plot(one_trained_model.history['val_loss'], label="Validation Loss")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training and Validation Loss Values Over Epochs")
plt.legend()
plt.show()

In [ ]:
#Obtain weight and bias
weights, bias = one_model.layers[0].get_weights()

#calulate train and test mse

one_train_mse = one_model.evaluate(
    one_X_train_scaled,
    one_y_train,
    verbose = 0 #supress output
)

#Calculate test MSE
one_test_mse = one_model.evaluate(
    one_X_test_scaled,
    one_y_test,
    verbose = 0 # supress output
)

# Learned parameters
print(f"Learned Weights:\n{weights}")
print(f"\nLearned Bias:\n{bias}")

print(f"Train MSE (standardized): {one_train_mse:.3f}")
print(f"Test MSE (standardized): {one_test_mse:.3f}")
print(f"Difference between test and train MSE: {abs(one_train_mse - one_test_mse):.3f}")