In [1]:
#Upload Libraries

import numpy as np
import pandas as pd
import glob

In [2]:
# Arrivals Data from US DOT by Site

# Get only real CSV files, not Zone.Identifier files
USDOT = [
    file for file in glob.glob("data/Departures_data_by_airport/*.csv")
    if not file.endswith(":Zone.Identifier")
]

#verfiy number of files found
print("Files found:", len(USDOT))
print(USDOT)

#skip the first 7 rows of non-data
df = pd.concat(
    [pd.read_csv(file, skiprows=7, skipfooter=1, engine="python") for file in USDOT],
    ignore_index=True
)

print(df.shape)
df.head()

#export to .csv file
#df.to_csv("DEN_departures.csv", index=False)

Files found: 4
['data/Departures_data_by_airport/AA_Detailed_Statistics_Departures.csv', 'data/Departures_data_by_airport/UA_Detailed_Statistics_Departures.csv', 'data/Departures_data_by_airport/DL_Detailed_Statistics_Departures.csv', 'data/Departures_data_by_airport/WN_Detailed_Statistics_Departures.csv']
(898146, 17)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,AA,01/01/2022,378,N827NN,MIA,14:03,14:00,236,232,-3,14:18,18,0,0,0,0,0
1,AA,01/01/2022,500,N938AN,MIA,00:45,00:57,238,269,12,01:53,56,12,0,31,0,0
2,AA,01/01/2022,573,N874NN,CLT,06:25,06:40,204,220,15,07:17,37,15,0,16,0,0
3,AA,01/01/2022,707,N198UW,PHX,07:00,07:46,139,163,46,08:54,68,46,0,24,0,0
4,AA,01/01/2022,744,N956AN,ORD,08:15,08:24,163,191,9,09:28,64,0,9,28,0,0

In [3]:
# Weather info in DEN International airport

# NOAA weather files
weather_files = glob.glob("data/weather_info_by_year/*.psv")

print("Files found:", len(weather_files))
print(weather_files)

# Load and append all weather files
weather_df = pd.concat(
    [pd.read_csv(file, sep="|") for file in weather_files],
    ignore_index=True
)

print(weather_df.shape)
weather_df.head()

#export to .csv file
#df.to_csv("DEN_weather.csv", index=False)

Files found: 5
['data/weather_info_by_year/GHCNh_USW00003017_2023.psv', 'data/weather_info_by_year/GHCNh_USW00003017_2022.psv', 'data/weather_info_by_year/GHCNh_USW00003017_2026.psv', 'data/weather_info_by_year/GHCNh_USW00003017_2025.psv', 'data/weather_info_by_year/GHCNh_USW00003017_2024.psv']

/tmp/ipykernel_10482/778604599.py:11: DtypeWarning: Columns (0: temperature_Quality_Code, 1: dew_point_temperature_Quality_Code, 2: wind_speed_Quality_Code, 3: pres_wx_MW2, 4: pres_wx_MW2_Report_Type, 5: pres_wx_MW2_Source_Station_ID, 6: pres_wx_MW3, 7: pres_wx_MW3_Report_Type, 8: pres_wx_MW3_Source_Station_ID, 9: pres_wx_AU2_Quality_Code, 10: pres_wx_AU3, 11: pres_wx_AU3_Quality_Code, 12: pres_wx_AU3_Report_Type, 13: pres_wx_AU3_Source_Station_ID, 14: pres_wx_AW3, 15: pres_wx_AW3_Report_Type, 16: pres_wx_AW3_Source_Station_ID, 17: sky_cover_summation_1_Quality_Code, 18: sky_cover_summation_2_Quality_Code, 19: sky_cover_summation_3_Quality_Code, 20: sky_cover_summation_baseht_1_Quality_Code, 21: sky_cover_summation_baseht_2_Quality_Code, 22: sky_cover_summation_baseht_3_Quality_Code) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file, sep="|") for file in weather_files],
/tmp/ipykernel_10482/778604599.py:11: DtypeWarning: Columns (0: temperature_Quality_Code, 1: dew_point_temperature_Quality_Code, 2: wind_speed_Quality_Code, 3: precipitation_Quality_Code, 4: pres_wx_MW2, 5: pres_wx_MW2_Report_Type, 6: pres_wx_MW2_Source_Station_ID, 7: pres_wx_AU3, 8: pres_wx_AU3_Quality_Code, 9: pres_wx_AU3_Report_Type, 10: pres_wx_AU3_Source_Station_ID, 11: pres_wx_AW3, 12: pres_wx_AW3_Report_Type, 13: pres_wx_AW3_Source_Station_ID, 14: visibility_Quality_Code, 15: sky_cover_summation_1_Quality_Code, 16: sky_cover_summation_2_Quality_Code, 17: sky_cover_summation_3_Quality_Code, 18: sky_cover_summation_baseht_1_Quality_Code, 19: sky_cover_summation_baseht_2_Quality_Code, 20: sky_cover_summation_baseht_3_Quality_Code) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file, sep="|") for file in weather_files],
/tmp/ipykernel_10482/778604599.py:11: DtypeWarning: Columns (0: station_level_pressure_Measurement_Code, 1: wind_direction_Measurement_Code, 2: wind_speed_Measurement_Code, 3: precipitation_Measurement_Code, 4: precipitation_Report_Type, 5: precipitation_Source_Station_ID, 6: relative_humidity_Quality_Code, 7: pres_wx_MW1, 8: pres_wx_MW1_Report_Type, 9: pres_wx_MW1_Source_Station_ID, 10: pres_wx_MW2, 11: pres_wx_MW2_Report_Type, 12: pres_wx_MW2_Source_Station_ID, 13: pres_wx_MW3, 14: pres_wx_MW3_Report_Type, 15: pres_wx_MW3_Source_Station_ID, 16: pres_wx_AU1, 17: pres_wx_AU1_Report_Type, 18: pres_wx_AU1_Source_Station_ID, 19: pres_wx_AU2, 20: pres_wx_AU2_Report_Type, 21: pres_wx_AU2_Source_Station_ID, 22: pres_wx_AU3, 23: pres_wx_AU3_Report_Type, 24: pres_wx_AU3_Source_Station_ID, 25: pres_wx_AW1, 26: pres_wx_AW1_Report_Type, 27: pres_wx_AW1_Source_Station_ID, 28: pres_wx_AW2, 29: pres_wx_AW2_Report_Type, 30: pres_wx_AW2_Source_Station_ID, 31: pres_wx_AW3, 32: pres_wx_AW3_Report_Type, 33: pres_wx_AW3_Source_Station_ID, 34: visibility_Measurement_Code, 35: sky_condition, 36: sky_condition_Quality_Code, 37: sky_condition_Report_Type, 38: sky_condition_Source_Station_ID, 39: sky_condition_baseht_Measurement_Code, 40: sky_condition_baseht_Report_Type, 41: sky_condition_baseht_Source_Station_ID, 42: sky_cover_layer_baseht_1_Measurement_Code, 43: sky_cover_layer_baseht_1_Report_Type, 44: sky_cover_layer_baseht_1_Source_Station_ID, 45: sky_cover_summation_4, 46: sky_cover_summation_4_Report_Type, 47: sky_cover_summation_4_Source_Station_ID, 48: sky_cover_summation_baseht_1_Measurement_Code, 49: sky_cover_summation_baseht_2_Measurement_Code, 50: sky_cover_summation_baseht_3_Measurement_Code, 51: sky_cover_summation_baseht_4_Measurement_Code, 52: sky_cover_summation_baseht_4_Report_Type, 53: sky_cover_summation_baseht_4_Source_Station_ID, 54: precipitation_5_minute_Measurement_Code, 55: precipitation_3_hour_Measurement_Code, 56: precipitation_3_hour_Report_Type, 57: precipitation_3_hour_Source_Station_ID, 58: precipitation_6_hour_Measurement_Code, 59: precipitation_6_hour_Report_Type, 60: precipitation_6_hour_Source_Station_ID, 61: precipitation_24_hour_Report_Type, 62: precipitation_24_hour_Source_Station_ID) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file, sep="|") for file in weather_files],
/tmp/ipykernel_10482/778604599.py:11: DtypeWarning: Columns (0: wet_bulb_temperature_Quality_Code, 1: pres_wx_MW2, 2: pres_wx_MW2_Report_Type, 3: pres_wx_MW2_Source_Station_ID, 4: pres_wx_AU1, 5: pres_wx_AU1_Report_Type, 6: pres_wx_AU1_Source_Station_ID, 7: pres_wx_AU2, 8: pres_wx_AU2_Report_Type, 9: pres_wx_AU2_Source_Station_ID, 10: pres_wx_AU3, 11: pres_wx_AU3_Report_Type, 12: pres_wx_AU3_Source_Station_ID, 13: pres_wx_AW3, 14: pres_wx_AW3_Report_Type, 15: pres_wx_AW3_Source_Station_ID, 16: sky_cover_summation_baseht_1_Measurement_Code, 17: sky_cover_summation_baseht_2_Measurement_Code, 18: sky_cover_summation_baseht_3_Measurement_Code) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file, sep="|") for file in weather_files],
/tmp/ipykernel_10482/778604599.py:11: DtypeWarning: Columns (0: temperature_Quality_Code, 1: dew_point_temperature_Quality_Code, 2: wind_speed_Quality_Code, 3: relative_humidity_Quality_Code, 4: wet_bulb_temperature_Quality_Code, 5: pres_wx_MW2, 6: pres_wx_MW2_Report_Type, 7: pres_wx_MW2_Source_Station_ID, 8: pres_wx_AU1_Quality_Code, 9: pres_wx_AU2, 10: pres_wx_AU2_Quality_Code, 11: pres_wx_AU2_Report_Type, 12: pres_wx_AU2_Source_Station_ID, 13: pres_wx_AU3, 14: pres_wx_AU3_Quality_Code, 15: pres_wx_AU3_Report_Type, 16: pres_wx_AU3_Source_Station_ID, 17: pres_wx_AW2, 18: pres_wx_AW2_Report_Type, 19: pres_wx_AW2_Source_Station_ID, 20: pres_wx_AW3, 21: pres_wx_AW3_Report_Type, 22: pres_wx_AW3_Source_Station_ID, 23: visibility_Quality_Code, 24: sky_cover_summation_1_Quality_Code, 25: sky_cover_summation_2_Quality_Code, 26: sky_cover_summation_3_Quality_Code, 27: sky_cover_summation_baseht_1_Quality_Code, 28: sky_cover_summation_baseht_2_Quality_Code, 29: sky_cover_summation_baseht_3_Quality_Code, 30: precipitation_24_hour_Report_Type, 31: precipitation_24_hour_Source_Station_ID) have mixed types. Specify dtype option on import or set low_memory=False.
  [pd.read_csv(file, sep="|") for file in weather_files],

(96229, 329)

,STATION,Station_name,DATE,Year,Month,Day,Hour,Minute,LATITUDE,LONGITUDE,...,precipitation_24_hour_Quality_Code,precipitation_24_hour_Report_Type,precipitation_24_hour_Source_Code,precipitation_24_hour_Source_Station_ID,REM,REM_Measurement_Code,REM_Quality_Code,REM_Report_Type,REM_Source_Code,REM_Source_Station_ID
0,USW00003017,DENVER INTL AP,2023-01-01T00:00:00,2023,1,1,0,0,39.8467,-104.6561,...,NaN,NaN,NaN,NaN,SYN08072565 32866 41307 10011 21022 38245 4006...,NaN,NaN,FM12,223.0,ICAO-KDEN
1,USW00003017,DENVER INTL AP,2023-01-01T00:53:00,2023,1,1,0,53,39.8467,-104.6561,...,NaN,NaN,NaN,NaN,MET11412/31/22 17:53:03 METAR KDEN 010053Z 140...,NaN,NaN,FM15,343.0,725650-03017
2,USW00003017,DENVER INTL AP,2023-01-01T01:53:00,2023,1,1,1,53,39.8467,-104.6561,...,NaN,NaN,NaN,NaN,MET10712/31/22 18:53:03 METAR KDEN 010153Z 140...,NaN,NaN,FM15,343.0,725650-03017
3,USW00003017,DENVER INTL AP,2023-01-01T02:53:00,2023,1,1,2,53,39.8467,-104.6561,...,NaN,NaN,NaN,NaN,MET10612/31/22 19:53:03 METAR KDEN 010253Z 130...,NaN,NaN,FM15,343.0,725650-03017
4,USW00003017,DENVER INTL AP,2023-01-01T03:00:00,2023,1,1,3,0,39.8467,-104.6561,...,NaN,NaN,NaN,NaN,SYN06472565 32966 61305 10000 21044 38256 4007...,NaN,NaN,FM12,223.0,ICAO-KDEN

In [4]:
#aircraft information

aircraft_master = pd.read_csv(
    "data/Aircraft Information/MASTER.txt",
    dtype=str
)

print(aircraft_master.shape)
aircraft_master.head()

#export to .csv file
#df.to_csv("aircraft_info.csv", index=False)

(313930, 35)

,N-NUMBER,SERIAL NUMBER,MFR MDL CODE,ENG MFR MDL,YEAR MFR,TYPE REGISTRANT,NAME,STREET,STREET2,CITY,...,OTHER NAMES(2),OTHER NAMES(3),OTHER NAMES(4),OTHER NAMES(5),EXPIRATION DATE,UNIQUE ID,KIT MFR,KIT MODEL,MODE S CODE HEX,Unnamed: 34
0,100,5334,7100510,17003,1940,1,BENE MARY D ...,PO BOX 329,,KETCHUM,...,...,...,...,...,20270430,00600060,,,A004B3,NaN
1,10000,10000,2130004,,,7,9AT LLC ...,511 WEDGEWOOD AVE,,NASHVILLE,...,...,...,...,...,20310831,01443200,,,A00725,NaN
2,10001,A28,9601202,67007,1928,1,STOOS ROBERT A ...,PO BOX 1056,,LAKELAND,...,...,...,...,...,20290228,00432072,,,A00726,NaN
3,10004,T18208245,2072738,,,7,ETOS AIR LLC ...,PO BOX 288,,NEW LONDON,...,...,...,...,...,20290331,00102879,,,A00729,NaN
4,10006,BG-72,1152020,17026,1955,1,COUTCHES ROBERT HERCULES DBA ...,550 AIRWAY BLVD,,LIVERMORE,...,...,...,...,...,20280229,00480110,,,A0072B,NaN

In [5]:
#Column Names and Datatype
print("Arrivals Data Columns and Data Types")
print(df.dtypes)

Arrivals Data Columns and Data Types
Carrier Code                                  str
Date (MM/DD/YYYY)                             str
Flight Number                               int64
Tail Number                                   str
Destination Airport                           str
Scheduled departure time                      str
Actual departure time                         str
Scheduled elapsed time (Minutes)            int64
Actual elapsed time (Minutes)               int64
Departure delay (Minutes)                   int64
Wheels-off time                               str
Taxi-Out time (Minutes)                     int64
Delay Carrier (Minutes)                     int64
Delay Weather (Minutes)                     int64
Delay National Aviation System (Minutes)    int64
Delay Security (Minutes)                    int64
Delay Late Aircraft Arrival (Minutes)       int64
dtype: object

In [6]:
print("\nWeather Data Columns and Data Types")
print(weather_df.dtypes)

Weather Data Columns and Data Types
STATION                      str
Station_name                 str
DATE                         str
Year                       int64
Month                      int64
                          ...
REM_Measurement_Code     float64
REM_Quality_Code         float64
REM_Report_Type              str
REM_Source_Code          float64
REM_Source_Station_ID        str
Length: 329, dtype: object

In [7]:
print("\nAircraft Master Data Columns and Data Types")
print(aircraft_master.dtypes)

Aircraft Master Data Columns and Data Types
N-NUMBER            str
SERIAL NUMBER       str
MFR MDL CODE        str
ENG MFR MDL         str
YEAR MFR            str
TYPE REGISTRANT     str
NAME                str
STREET              str
STREET2             str
CITY                str
STATE               str
ZIP CODE            str
REGION              str
COUNTY              str
COUNTRY             str
LAST ACTION DATE    str
CERT ISSUE DATE     str
CERTIFICATION       str
TYPE AIRCRAFT       str
TYPE ENGINE         str
STATUS CODE         str
MODE S CODE         str
FRACT OWNER         str
AIR WORTH DATE      str
OTHER NAMES(1)      str
OTHER NAMES(2)      str
OTHER NAMES(3)      str
OTHER NAMES(4)      str
OTHER NAMES(5)      str
EXPIRATION DATE     str
UNIQUE ID           str
KIT MFR             str
 KIT MODEL          str
MODE S CODE HEX     str
Unnamed: 34         str
dtype: object