In [8]:
#Load Libraries

import pandas as pd

In [10]:
#Load data
NOAA_SFO_df = pd.read_csv(
    "../Data_Extraction/SFO_NOAA_raw_YvonneChook/NOAA_SFO_2022_2026.csv"
)

NOAA_SFO_df.head()

/tmp/ipykernel_18022/67462777.py:2: DtypeWarning: Columns (0: temperature_Quality_Code, 1: dew_point_temperature_Quality_Code, 2: station_level_pressure_Measurement_Code, 3: wind_direction_Measurement_Code, 4: wind_speed_Measurement_Code, 5: wind_speed_Quality_Code, 6: wind_gust_Report_Type, 7: wind_gust_Source_Station_ID, 8: precipitation_Measurement_Code, 9: precipitation_Quality_Code, 10: precipitation_Report_Type, 11: precipitation_Source_Station_ID, 12: relative_humidity_Quality_Code, 13: wet_bulb_temperature_Quality_Code, 14: pres_wx_MW1, 15: pres_wx_MW1_Report_Type, 16: pres_wx_MW1_Source_Station_ID, 17: pres_wx_MW2, 18: pres_wx_MW2_Report_Type, 19: pres_wx_MW2_Source_Station_ID, 20: pres_wx_MW3, 21: pres_wx_MW3_Report_Type, 22: pres_wx_MW3_Source_Station_ID, 23: pres_wx_AU1, 24: pres_wx_AU1_Quality_Code, 25: pres_wx_AU1_Report_Type, 26: pres_wx_AU1_Source_Station_ID, 27: pres_wx_AU2, 28: pres_wx_AU2_Report_Type, 29: pres_wx_AU2_Source_Station_ID, 30: pres_wx_AU3, 31: pres_wx_AU3_Report_Type, 32: pres_wx_AU3_Source_Station_ID, 33: pres_wx_AW1, 34: pres_wx_AW1_Report_Type, 35: pres_wx_AW1_Source_Station_ID, 36: pres_wx_AW2, 37: pres_wx_AW2_Report_Type, 38: pres_wx_AW2_Source_Station_ID, 39: pres_wx_AW3, 40: pres_wx_AW3_Report_Type, 41: pres_wx_AW3_Source_Station_ID, 42: visibility_Measurement_Code, 43: visibility_Quality_Code, 44: sky_condition, 45: sky_condition_Quality_Code, 46: sky_condition_Report_Type, 47: sky_condition_Source_Station_ID, 48: sky_condition_baseht_Measurement_Code, 49: sky_condition_baseht_Report_Type, 50: sky_condition_baseht_Source_Station_ID, 51: sky_cover_layer_baseht_1_Measurement_Code, 52: sky_cover_layer_baseht_1_Report_Type, 53: sky_cover_layer_baseht_1_Source_Station_ID, 54: sky_cover_summation_1_Quality_Code, 55: sky_cover_summation_2_Quality_Code, 56: sky_cover_summation_3, 57: sky_cover_summation_3_Report_Type, 58: sky_cover_summation_3_Source_Station_ID, 59: sky_cover_summation_4, 60: sky_cover_summation_4_Report_Type, 61: sky_cover_summation_4_Source_Station_ID, 62: sky_cover_summation_baseht_1_Measurement_Code, 63: sky_cover_summation_baseht_1_Quality_Code, 64: sky_cover_summation_baseht_2_Measurement_Code, 65: sky_cover_summation_baseht_2_Quality_Code, 66: sky_cover_summation_baseht_3_Measurement_Code, 67: sky_cover_summation_baseht_3_Report_Type, 68: sky_cover_summation_baseht_3_Source_Station_ID, 69: sky_cover_summation_baseht_4_Measurement_Code, 70: sky_cover_summation_baseht_4_Report_Type, 71: sky_cover_summation_baseht_4_Source_Station_ID, 72: precipitation_5_minute_Measurement_Code, 73: precipitation_3_hour_Measurement_Code, 74: precipitation_3_hour_Report_Type, 75: precipitation_3_hour_Source_Station_ID, 76: precipitation_6_hour_Measurement_Code, 77: precipitation_6_hour_Report_Type, 78: precipitation_6_hour_Source_Station_ID, 79: precipitation_24_hour_Report_Type, 80: precipitation_24_hour_Source_Station_ID) have mixed types. Specify dtype option on import or set low_memory=False.
  NOAA_SFO_df = pd.read_csv(

,STATION,Station_name,DATE,Year,Month,Day,Hour,Minute,LATITUDE,LONGITUDE,...,precipitation_24_hour_Quality_Code,precipitation_24_hour_Report_Type,precipitation_24_hour_Source_Code,precipitation_24_hour_Source_Station_ID,REM,REM_Measurement_Code,REM_Quality_Code,REM_Report_Type,REM_Source_Code,REM_Source_Station_ID
0,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T00:00:00,2024,1,1,0,0,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,SYN08072494 32666 80204 10133 20100 30154 4018...,NaN,NaN,FM12,223.0,ICAO-KSFO
1,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T00:56:00,2024,1,1,0,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET083METAR KSFO 010056Z 01004KT 10SM FEW040 B...,NaN,NaN,FM15,223.0,ICAO-KSFO
2,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T01:56:00,2024,1,1,1,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET083METAR KSFO 010156Z 00000KT 10SM FEW040 B...,NaN,NaN,FM15,223.0,ICAO-KSFO
3,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T02:56:00,2024,1,1,2,56,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,MET096METAR KSFO 010256Z 00000KT 10SM FEW020 S...,NaN,NaN,FM15,223.0,ICAO-KSFO
4,USW00023234,SAN FRANCISCO INTL AP,2024-01-01T03:00:00,2024,1,1,3,0,37.6197,-122.3656,...,NaN,NaN,NaN,NaN,SYN06472494 32566 60000 10128 20094 30158 4018...,NaN,NaN,FM12,223.0,ICAO-KSFO

**Review Data available**

In [29]:
#Check shape 
print("NOAA Extract Shape:")
print(NOAA_SFO_df.shape)

NOAA Extract Shape:
(89176, 329)

In [25]:
# Review NOAA SFO dataset info
NOAA_summary = pd.DataFrame({
    "column_name": NOAA_SFO_df.columns,
    "dtype": NOAA_SFO_df.dtypes.values,
    "nulls_count": NOAA_SFO_df.isna().sum().values,
    "nulls_percent": (NOAA_SFO_df.isna().mean().values * 100).round(3),
    "unique_values": NOAA_SFO_df.nunique().values
})

display(NOAA_summary)

,column_name,dtype,nulls_count,nulls_percent,unique_values
0,STATION,str,0,0.000,1
1,Station_name,str,0,0.000,1
2,DATE,datetime64[us],0,0.000,89176
3,Year,int64,0,0.000,5
4,Month,int64,0,0.000,12
5,Day,int64,0,0.000,31
6,Hour,int64,0,0.000,24
7,Minute,int64,0,0.000,60
8,LATITUDE,float64,0,0.000,1
9,LONGITUDE,float64,0,0.000,1
10,ELEVATION,float64,0,0.000,1
11,temperature,float64,35391,39.687,83
12,temperature_Measurement_Code,float64,89176,100.000,0
13,temperature_Quality_Code,object,37412,41.953,7
14,temperature_Report_Type,str,35391,39.687,3
15,temperature_Source_Code,float64,35391,39.687,3
16,temperature_Source_Station_ID,str,35391,39.687,2
17,dew_point_temperature,float64,35391,39.687,72
18,dew_point_temperature_Measurement_Code,float64,89176,100.000,0
19,dew_point_temperature_Quality_Code,object,37412,41.953,7
20,dew_point_temperature_Report_Type,str,35391,39.687,3
21,dew_point_temperature_Source_Code,float64,35391,39.687,3
22,dew_point_temperature_Source_Station_ID,str,35391,39.687,2
23,station_level_pressure,float64,41563,46.608,253
24,station_level_pressure_Measurement_Code,str,87133,97.709,1
25,station_level_pressure_Quality_Code,float64,43606,48.899,2
26,station_level_pressure_Report_Type,str,41563,46.608,3
27,station_level_pressure_Source_Code,float64,41563,46.608,3
28,station_level_pressure_Source_Station_ID,str,41563,46.608,2
29,sea_level_pressure,float64,40957,45.928,374
30,sea_level_pressure_Measurement_Code,float64,89176,100.000,0
31,sea_level_pressure_Quality_Code,float64,42744,47.932,3
32,sea_level_pressure_Report_Type,str,40957,45.928,2
33,sea_level_pressure_Source_Code,float64,40957,45.928,3
34,sea_level_pressure_Source_Station_ID,str,40957,45.928,2
35,wind_direction,float64,35410,39.708,38
36,wind_direction_Measurement_Code,str,37418,41.960,3
37,wind_direction_Quality_Code,float64,39352,44.128,3
38,wind_direction_Report_Type,str,35410,39.708,3
39,wind_direction_Source_Code,float64,35410,39.708,3
40,wind_direction_Source_Station_ID,str,35410,39.708,2
41,wind_speed,float64,35397,39.693,43
42,wind_speed_Measurement_Code,str,37418,41.960,3
43,wind_speed_Quality_Code,object,37418,41.960,6
44,wind_speed_Report_Type,str,35397,39.693,3
45,wind_speed_Source_Code,float64,35397,39.693,3
46,wind_speed_Source_Station_ID,str,35397,39.693,2
47,wind_gust,float64,83017,93.093,53
48,wind_gust_Measurement_Code,float64,89176,100.000,0
49,wind_gust_Quality_Code,float64,83384,93.505,2
50,wind_gust_Report_Type,str,83017,93.093,2
51,wind_gust_Source_Code,float64,83017,93.093,3
52,wind_gust_Source_Station_ID,str,83017,93.093,2
53,precipitation,float64,56049,62.852,72
54,precipitation_Measurement_Code,str,87587,98.218,1
55,precipitation_Quality_Code,object,56234,63.060,6
56,precipitation_Report_Type,str,56049,62.852,2
57,precipitation_Source_Code,float64,56049,62.852,3
58,precipitation_Source_Station_ID,str,56049,62.852,2
59,relative_humidity,float64,35391,39.687,84
60,relative_humidity_Measurement_Code,str,35391,39.687,1
61,relative_humidity_Quality_Code,str,89165,99.988,1
62,relative_humidity_Report_Type,str,35391,39.687,3
63,relative_humidity_Source_Code,float64,35391,39.687,3
64,relative_humidity_Source_Station_ID,str,35391,39.687,2
65,wet_bulb_temperature,float64,41565,46.610,212
66,wet_bulb_temperature_Measurement_Code,str,41565,46.610,1
67,wet_bulb_temperature_Quality_Code,str,89170,99.993,1
68,wet_bulb_temperature_Report_Type,str,41565,46.610,3
69,wet_bulb_temperature_Source_Code,float64,41565,46.610,3
70,wet_bulb_temperature_Source_Station_ID,str,41565,46.610,2
71,pres_wx_MW1,str,86224,96.690,12
72,pres_wx_MW1_Measurement_Code,float64,89176,100.000,0
73,pres_wx_MW1_Quality_Code,float64,86337,96.816,2
74,pres_wx_MW1_Report_Type,str,86224,96.690,3
75,pres_wx_MW1_Source_Code,float64,86224,96.690,3
76,pres_wx_MW1_Source_Station_ID,str,86224,96.690,2
77,pres_wx_MW2,str,89174,99.998,2
78,pres_wx_MW2_Measurement_Code,float64,89176,100.000,0
79,pres_wx_MW2_Quality_Code,float64,89175,99.999,1
80,pres_wx_MW2_Report_Type,str,89174,99.998,2
81,pres_wx_MW2_Source_Code,float64,89174,99.998,2
82,pres_wx_MW2_Source_Station_ID,str,89174,99.998,2
83,pres_wx_MW3,str,89173,99.997,1
84,pres_wx_MW3_Measurement_Code,float64,89176,100.000,0
85,pres_wx_MW3_Quality_Code,float64,89176,100.000,0
86,pres_wx_MW3_Report_Type,str,89173,99.997,2
87,pres_wx_MW3_Source_Code,float64,89173,99.997,1
88,pres_wx_MW3_Source_Station_ID,str,89173,99.997,1
89,pres_wx_AU1,str,86182,96.643,14
90,pres_wx_AU1_Measurement_Code,float64,89176,100.000,0
91,pres_wx_AU1_Quality_Code,object,86296,96.770,5
92,pres_wx_AU1_Report_Type,str,86182,96.643,2
93,pres_wx_AU1_Source_Code,float64,86182,96.643,2
94,pres_wx_AU1_Source_Station_ID,str,86182,96.643,2
95,pres_wx_AU2,str,88290,99.006,8
96,pres_wx_AU2_Measurement_Code,float64,89176,100.000,0
97,pres_wx_AU2_Quality_Code,float64,88319,99.039,1
98,pres_wx_AU2_Report_Type,str,88290,99.006,2
99,pres_wx_AU2_Source_Code,float64,88290,99.006,2
100,pres_wx_AU2_Source_Station_ID,str,88290,99.006,2
101,pres_wx_AU3,str,89167,99.990,2
102,pres_wx_AU3_Measurement_Code,float64,89176,100.000,0
103,pres_wx_AU3_Quality_Code,float64,89170,99.993,1
104,pres_wx_AU3_Report_Type,str,89167,99.990,2
105,pres_wx_AU3_Source_Code,float64,89167,99.990,2
106,pres_wx_AU3_Source_Station_ID,str,89167,99.990,2
107,pres_wx_AW1,str,85573,95.960,12
108,pres_wx_AW1_Measurement_Code,float64,89176,100.000,0
109,pres_wx_AW1_Quality_Code,float64,85687,96.088,3
110,pres_wx_AW1_Report_Type,str,85573,95.960,2
111,pres_wx_AW1_Source_Code,float64,85573,95.960,3
112,pres_wx_AW1_Source_Station_ID,str,85573,95.960,2
113,pres_wx_AW2,str,88105,98.799,8
114,pres_wx_AW2_Measurement_Code,float64,89176,100.000,0
115,pres_wx_AW2_Quality_Code,float64,88134,98.832,2
116,pres_wx_AW2_Report_Type,str,88105,98.799,2
117,pres_wx_AW2_Source_Code,float64,88105,98.799,3
118,pres_wx_AW2_Source_Station_ID,str,88105,98.799,2
119,pres_wx_AW3,str,89166,99.989,3
120,pres_wx_AW3_Measurement_Code,float64,89176,100.000,0
121,pres_wx_AW3_Quality_Code,float64,89169,99.992,2
122,pres_wx_AW3_Report_Type,str,89166,99.989,2
123,pres_wx_AW3_Source_Code,float64,89166,99.989,3
124,pres_wx_AW3_Source_Station_ID,str,89166,99.989,2
125,snow_depth,float64,89176,100.000,0
126,snow_depth_Measurement_Code,float64,89176,100.000,0
127,snow_depth_Quality_Code,float64,89176,100.000,0
128,snow_depth_Report_Type,float64,89176,100.000,0
129,snow_depth_Source_Code,float64,89176,100.000,0
130,snow_depth_Source_Station_ID,float64,89176,100.000,0
131,visibility,float64,35390,39.686,48
132,visibility_Measurement_Code,str,37411,41.952,3
133,visibility_Quality_Code,object,37411,41.952,7
134,visibility_Report_Type,str,35390,39.686,3
135,visibility_Source_Code,float64,35390,39.686,3
136,visibility_Source_Station_ID,str,35390,39.686,2
137,altimeter,float64,44887,50.335,138
138,altimeter_Measurement_Code,float64,89176,100.000,0
139,altimeter_Quality_Code,float64,46908,52.602,2
140,altimeter_Report_Type,str,44887,50.335,2
141,altimeter_Source_Code,float64,44887,50.335,3
142,altimeter_Source_Station_ID,str,44887,50.335,2
143,pressure_3hr_change,float64,67861,76.098,98
144,pressure_3hr_change_Measurement_Code,float64,67861,76.098,9
145,pressure_3hr_change_Quality_Code,float64,68457,76.766,2
146,pressure_3hr_change_Report_Type,str,67861,76.098,2
147,pressure_3hr_change_Source_Code,float64,67861,76.098,3
148,pressure_3hr_change_Source_Station_ID,str,67861,76.098,2
149,sky_condition,str,62696,70.306,6
150,sky_condition_Measurement_Code,float64,89176,100.000,0
151,sky_condition_Quality_Code,str,62696,70.306,2
152,sky_condition_Report_Type,str,62696,70.306,3
153,sky_condition_Source_Code,float64,62696,70.306,1
154,sky_condition_Source_Station_ID,str,62696,70.306,1
155,sky_condition_baseht,float64,46714,52.384,83
156,sky_condition_baseht_Measurement_Code,str,46714,52.384,1
157,sky_condition_baseht_Quality_Code,float64,46714,52.384,1
158,sky_condition_baseht_Report_Type,str,46714,52.384,3
159,sky_condition_baseht_Source_Code,float64,46714,52.384,1
160,sky_condition_baseht_Source_Station_ID,str,46714,52.384,1
161,ceiling_height,float64,43701,49.005,80
162,ceiling_height_Measurement_Code,str,43701,49.005,4
163,ceiling_height_Quality_Code,float64,44758,50.191,5
164,ceiling_height_Report_Type,str,43701,49.005,3
165,ceiling_height_Source_Code,float64,43701,49.005,3
166,ceiling_height_Source_Station_ID,str,43701,49.005,2
167,sky_cover_layer_1,float64,89176,100.000,0
168,sky_cover_layer_1_Measurement_Code,float64,89176,100.000,0
169,sky_cover_layer_1_Quality_Code,float64,89176,100.000,0
170,sky_cover_layer_1_Report_Type,float64,89176,100.000,0
171,sky_cover_layer_1_Source_Code,float64,89176,100.000,0
172,sky_cover_layer_1_Source_Station_ID,float64,89176,100.000,0
173,sky_cover_layer_2,float64,89176,100.000,0
174,sky_cover_layer_2_Measurement_Code,float64,89176,100.000,0
175,sky_cover_layer_2_Quality_Code,float64,89176,100.000,0
176,sky_cover_layer_2_Report_Type,float64,89176,100.000,0
177,sky_cover_layer_2_Source_Code,float64,89176,100.000,0
178,sky_cover_layer_2_Source_Station_ID,float64,89176,100.000,0
179,sky_cover_layer_3,float64,89176,100.000,0
180,sky_cover_layer_3_Measurement_Code,float64,89176,100.000,0
181,sky_cover_layer_3_Quality_Code,float64,89176,100.000,0
182,sky_cover_layer_3_Report_Type,float64,89176,100.000,0
183,sky_cover_layer_3_Source_Code,float64,89176,100.000,0
184,sky_cover_layer_3_Source_Station_ID,float64,89176,100.000,0
185,sky_cover_layer_4,float64,89176,100.000,0
186,sky_cover_layer_4_Measurement_Code,float64,89176,100.000,0
187,sky_cover_layer_4_Quality_Code,float64,89176,100.000,0
188,sky_cover_layer_4_Report_Type,float64,89176,100.000,0
189,sky_cover_layer_4_Source_Code,float64,89176,100.000,0
190,sky_cover_layer_4_Source_Station_ID,float64,89176,100.000,0
191,sky_cover_layer_baseht_1,float64,82523,92.539,12
192,sky_cover_layer_baseht_1_Measurement_Code,str,82523,92.539,1
193,sky_cover_layer_baseht_1_Quality_Code,float64,82523,92.539,1
194,sky_cover_layer_baseht_1_Report_Type,str,82523,92.539,3
195,sky_cover_layer_baseht_1_Source_Code,float64,82523,92.539,1
196,sky_cover_layer_baseht_1_Source_Station_ID,str,82523,92.539,1
197,sky_cover_layer_baseht_2,float64,89176,100.000,0
198,sky_cover_layer_baseht_2_Measurement_Code,float64,89176,100.000,0
199,sky_cover_layer_baseht_2_Quality_Code,float64,89176,100.000,0
200,sky_cover_layer_baseht_2_Report_Type,float64,89176,100.000,0
201,sky_cover_layer_baseht_2_Source_Code,float64,89176,100.000,0
202,sky_cover_layer_baseht_2_Source_Station_ID,float64,89176,100.000,0
203,sky_cover_layer_baseht_3,float64,89176,100.000,0
204,sky_cover_layer_baseht_3_Measurement_Code,float64,89176,100.000,0
205,sky_cover_layer_baseht_3_Quality_Code,float64,89176,100.000,0
206,sky_cover_layer_baseht_3_Report_Type,float64,89176,100.000,0
207,sky_cover_layer_baseht_3_Source_Code,float64,89176,100.000,0
208,sky_cover_layer_baseht_3_Source_Station_ID,float64,89176,100.000,0
209,sky_cover_layer_baseht_4,float64,89176,100.000,0
210,sky_cover_layer_baseht_4_Measurement_Code,float64,89176,100.000,0
211,sky_cover_layer_baseht_4_Quality_Code,float64,89176,100.000,0
212,sky_cover_layer_baseht_4_Report_Type,float64,89176,100.000,0
213,sky_cover_layer_baseht_4_Source_Code,float64,89176,100.000,0
214,sky_cover_layer_baseht_4_Source_Station_ID,float64,89176,100.000,0
215,sky_cover_summation_1,str,45664,51.207,7
216,sky_cover_summation_1_Measurement_Code,float64,89176,100.000,0
217,sky_cover_summation_1_Quality_Code,object,47688,53.476,5
218,sky_cover_summation_1_Report_Type,str,45664,51.207,2
219,sky_cover_summation_1_Source_Code,float64,45664,51.207,3
220,sky_cover_summation_1_Source_Station_ID,str,45664,51.207,2
221,sky_cover_summation_2,str,64733,72.590,4
222,sky_cover_summation_2_Measurement_Code,float64,89176,100.000,0
223,sky_cover_summation_2_Quality_Code,object,66035,74.050,5
224,sky_cover_summation_2_Report_Type,str,64733,72.590,2
225,sky_cover_summation_2_Source_Code,float64,64733,72.590,3
226,sky_cover_summation_2_Source_Station_ID,str,64733,72.590,2
227,sky_cover_summation_3,str,79149,88.756,4
228,sky_cover_summation_3_Measurement_Code,float64,89176,100.000,0
229,sky_cover_summation_3_Quality_Code,float64,79680,89.351,2
230,sky_cover_summation_3_Report_Type,str,79149,88.756,2
231,sky_cover_summation_3_Source_Code,float64,79149,88.756,3
232,sky_cover_summation_3_Source_Station_ID,str,79149,88.756,2
233,sky_cover_summation_4,str,88895,99.685,4
234,sky_cover_summation_4_Measurement_Code,float64,89176,100.000,0
235,sky_cover_summation_4_Quality_Code,float64,88924,99.717,1
236,sky_cover_summation_4_Report_Type,str,88895,99.685,2
237,sky_cover_summation_4_Source_Code,float64,88895,99.685,2
238,sky_cover_summation_4_Source_Station_ID,str,88895,99.685,1
239,sky_cover_summation_baseht_1,float64,50082,56.161,75
240,sky_cover_summation_baseht_1_Measurement_Code,str,55498,62.234,4
241,sky_cover_summation_baseht_1_Quality_Code,object,51982,58.291,5
242,sky_cover_summation_baseht_1_Report_Type,str,50082,56.161,2
243,sky_cover_summation_baseht_1_Source_Code,float64,50082,56.161,3
244,sky_cover_summation_baseht_1_Source_Station_ID,str,50082,56.161,2
245,sky_cover_summation_baseht_2,float64,64733,72.590,73
246,sky_cover_summation_baseht_2_Measurement_Code,str,68264,76.550,4
247,sky_cover_summation_baseht_2_Quality_Code,object,66035,74.050,5
248,sky_cover_summation_baseht_2_Report_Type,str,64733,72.590,2
249,sky_cover_summation_baseht_2_Source_Code,float64,64733,72.590,3
250,sky_cover_summation_baseht_2_Source_Station_ID,str,64733,72.590,2
251,sky_cover_summation_baseht_3,float64,79149,88.756,73
252,sky_cover_summation_baseht_3_Measurement_Code,str,80728,90.527,2
253,sky_cover_summation_baseht_3_Quality_Code,float64,79680,89.351,2
254,sky_cover_summation_baseht_3_Report_Type,str,79149,88.756,2
255,sky_cover_summation_baseht_3_Source_Code,float64,79149,88.756,3
256,sky_cover_summation_baseht_3_Source_Station_ID,str,79149,88.756,2
257,sky_cover_summation_baseht_4,float64,88895,99.685,7
258,sky_cover_summation_baseht_4_Measurement_Code,str,89147,99.967,1
259,sky_cover_summation_baseht_4_Quality_Code,float64,88924,99.717,1
260,sky_cover_summation_baseht_4_Report_Type,str,88895,99.685,2
261,sky_cover_summation_baseht_4_Source_Code,float64,88895,99.685,2
262,sky_cover_summation_baseht_4_Source_Station_ID,str,88895,99.685,1
263,precipitation_5_minute,float64,53214,59.673,13
264,precipitation_5_minute_Measurement_Code,str,87852,98.515,1
265,precipitation_5_minute_Quality_Code,float64,89176,100.000,0
266,precipitation_5_minute_Report_Type,float64,89176,100.000,0
267,precipitation_5_minute_Source_Code,float64,53214,59.673,1
268,precipitation_5_minute_Source_Station_ID,float64,53214,59.673,1
269,precipitation_15_minute,float64,89176,100.000,0
270,precipitation_15_minute_Measurement_Code,float64,89176,100.000,0
271,precipitation_15_minute_Quality_Code,float64,89176,100.000,0
272,precipitation_15_minute_Report_Type,float64,89176,100.000,0
273,precipitation_15_minute_Source_Code,float64,89176,100.000,0
274,precipitation_15_minute_Source_Station_ID,float64,89176,100.000,0
275,precipitation_3_hour,float64,88166,98.867,68
276,precipitation_3_hour_Measurement_Code,str,88834,99.616,1
277,precipitation_3_hour_Quality_Code,float64,88166,98.867,1
278,precipitation_3_hour_Report_Type,str,88166,98.867,2
279,precipitation_3_hour_Source_Code,float64,88166,98.867,1
280,precipitation_3_hour_Source_Station_ID,str,88166,98.867,1
281,precipitation_6_hour,float64,87634,98.271,104
282,precipitation_6_hour_Measurement_Code,str,88720,99.489,1
283,precipitation_6_hour_Quality_Code,float64,87634,98.271,1
284,precipitation_6_hour_Report_Type,str,87634,98.271,2
285,precipitation_6_hour_Source_Code,float64,87634,98.271,1
286,precipitation_6_hour_Source_Station_ID,str,87634,98.271,1
287,precipitation_9_hour,float64,89176,100.000,0
288,precipitation_9_hour_Measurement_Code,float64,89176,100.000,0
289,precipitation_9_hour_Quality_Code,float64,89176,100.000,0
290,precipitation_9_hour_Report_Type,float64,89176,100.000,0
291,precipitation_9_hour_Source_Code,float64,89176,100.000,0
292,precipitation_9_hour_Source_Station_ID,float64,89176,100.000,0
293,precipitation_12_hour,float64,89176,100.000,0
294,precipitation_12_hour_Measurement_Code,float64,89176,100.000,0
295,precipitation_12_hour_Quality_Code,float64,89176,100.000,0
296,precipitation_12_hour_Report_Type,float64,89176,100.000,0
297,precipitation_12_hour_Source_Code,float64,89176,100.000,0
298,precipitation_12_hour_Source_Station_ID,float64,89176,100.000,0
299,precipitation_15_hour,float64,89176,100.000,0
300,precipitation_15_hour_Measurement_Code,float64,89176,100.000,0
301,precipitation_15_hour_Quality_Code,float64,89176,100.000,0
302,precipitation_15_hour_Report_Type,float64,89176,100.000,0
303,precipitation_15_hour_Source_Code,float64,89176,100.000,0
304,precipitation_15_hour_Source_Station_ID,float64,89176,100.000,0
305,precipitation_18_hour,float64,89176,100.000,0
306,precipitation_18_hour_Measurement_Code,float64,89176,100.000,0
307,precipitation_18_hour_Quality_Code,float64,89176,100.000,0
308,precipitation_18_hour_Report_Type,float64,89176,100.000,0
309,precipitation_18_hour_Source_Code,float64,89176,100.000,0
310,precipitation_18_hour_Source_Station_ID,float64,89176,100.000,0
311,precipitation_21_hour,float64,89176,100.000,0
312,precipitation_21_hour_Measurement_Code,float64,89176,100.000,0
313,precipitation_21_hour_Quality_Code,float64,89176,100.000,0
314,precipitation_21_hour_Report_Type,float64,89176,100.000,0
315,precipitation_21_hour_Source_Code,float64,89176,100.000,0
316,precipitation_21_hour_Source_Station_ID,float64,89176,100.000,0
317,precipitation_24_hour,float64,88652,99.412,132
318,precipitation_24_hour_Measurement_Code,float64,89176,100.000,0
319,precipitation_24_hour_Quality_Code,float64,88652,99.412,1
320,precipitation_24_hour_Report_Type,str,88652,99.412,2
321,precipitation_24_hour_Source_Code,float64,88652,99.412,1
322,precipitation_24_hour_Source_Station_ID,str,88652,99.412,1
323,REM,str,35385,39.680,53791
324,REM_Measurement_Code,float64,89176,100.000,0
325,REM_Quality_Code,float64,89176,100.000,0
326,REM_Report_Type,str,35385,39.680,3
327,REM_Source_Code,float64,35385,39.680,3
328,REM_Source_Station_ID,str,35385,39.680,2

**Clean Data Type**

In [26]:
#Convert DATE column to datatime
NOAA_SFO_df["DATE"] = pd.to_datetime(NOAA_SFO_df["DATE"])

#check
NOAA_SFO_df["DATE"].dtype

dtype('<M8[us]')

In [28]:
# filter for unique entries only
NOAA_SFO_df = NOAA_SFO_df.drop_duplicates()

#Check shape
print(NOAA_SFO_df.shape)

(89176, 329)

**Comment:** No change in shape, indicating all entries have unique data combinations

**Filter to Relevant Data**

In [ ]:
#what filter should I put lol

**Sort Data**

In [32]:
#sort data from most recent to least recent
NOAA_SFO_df = NOAA_SFO_df.sort_values(
    by="DATE",
    ascending=False
).reset_index(drop=True)

#Check
NOAA_SFO_df[["DATE", "Year", "Month", "Day", "Hour", "Minute"]].head()

                 DATE  Year  Month  Day  Hour  Minute
0 2026-06-09 16:56:00  2026      6    9    16      56
1 2026-06-09 15:56:00  2026      6    9    15      56
2 2026-06-09 15:43:00  2026      6    9    15      43
3 2026-06-09 14:56:00  2026      6    9    14      56
4 2026-06-09 14:21:00  2026      6    9    14      21

**Save Data**

In [34]:
NOAA_SFO_df.to_csv("data/NOAA_SFO_2022_2026_cleaned.csv")